### ISSUE TITLE
Memory leak somewhere in DhcpServerClient.GetClients()

### ISSUE THREAD

**Issue by BenLorantfy** [garysharp/DhcpServerApi#1] opened 2016-03-14 20:31 UTC
If I use `DhcpServerClient.GetClients()` in my code, I can watch my process memory usage continuously increase until I stop and restart my process. I narrowed it down to somewhere in [here ](https://github.com/garysharp/DhcpServerApi/blob/master/src/Dhcp/DhcpServerClient.cs#L308-L347)but I'm not knoweldagable enough of the library at this point to fix it.

**Comment by BenLorantfy** [comment] 2016-03-15 13:57
I've narrowed it down to this line [here ](https://github.com/garysharp/DhcpServerApi/blob/master/src/Dhcp/DhcpServerClient.cs#L314) that is causing the memory leak.

**Comment by garysharp** [comment] 2016-03-16 23:15
Confirmed - I've been able to reproduce the leak. You would have noticed that an attempt is made to free the memory allocated by the native call [here](https://github.com/garysharp/DhcpServerApi/blob/09598f13eee50bfacb257be5ebed2ab5243b723e/src/Dhcp/DhcpServerClient.cs#L332). However it seems this isn't enough. All the allocated memory hasn't been released. I've done some preliminary investigation which indicates nested objects (including strings) may need to be released individually.
I'll try and put aside some time to investigate further over the coming days.
Thanks for your contribution @BenLorantfy

**Comment by garysharp** [comment] 2016-03-30 10:58
An initial attempt has been made to resolve the memory leak. This resolution is restricted just to the `DhcpServerClient.GetClients()` method at the moment. In my tests the method no longer leaks memory.

This work has been released to NuGet for testing:
https://www.nuget.org/packages/DhcpServerApi/0.2.1-alpha

I'd appreciate your feedback @BenLorantfy - if this mitigates the issue for you we'll have to organise applying the changes across all native structures in the library.

**Comment by garysharp** [comment] 2019-04-25 05:35
Some additional work will be done on this in [Version 1.0 Project](https://github.com/garysharp/DhcpServerApi/projects/1) - see #13 and #14. This issue will be closed due to lack of user feedback.

**Closed as completed by garysharp** 2019-04-25 05:35 UTC
Labels: bug
